coverage:
  status:
    project:
      default:
        # basic
        target: 75
        threshold: null
        base: auto 
    patch:
      default:
        # basic
        target: 75
        threshold: null
        base: auto 


ignore:
  - "tests/.*"  # ignore folders and all its contents